// Login 
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const USER_FOUND = 'USER_FOUND';
export const AUTH_ERROR = 'AUTH_ERROR';

// SignIn 
export const CLEAR_SIGNUP_DATA = 'CLEAR_SIGNUP_DATA'; 
export const START_STEP_ONE = 'START_STEP_ONE';
export const START_STEP_TWO = 'START_STEP_TWO';
export const START_STEP_THREE = 'START_STEP_THREE';
export const STOP_STEP_ONE = 'STOP_STEP_ONE';
export const STOP_STEP_TWO = 'STOP_STEP_TWO';
export const STOP_STEP_THREE = 'STOP_STEP_THREE';
export const ERROR_IN_STEP_ONE = 'ERROR_IN_STEP_ONE';
export const ERROR_IN_STEP_TWO = 'ERROR_IN_STEP_TWO';
export const ERROR_IN_STEP_THREE = 'ERROR_IN_STEP_THREE';
export const STEP_ONE_COMPLETED = 'STEP_ONE_COMPLETED';
export const STEP_TWO_COMPLETED = 'STEP_TWO_COMPLETED';
export const STEP_THREE_COMPLETED = 'STEP_THREE_COMPLETED';
export const PLANS_GETTED = 'PLANS_GETTED';
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';

// Forgot Password
export const SENDING_VERIFICATION_CODE = 'SENDING_VERIFICATION_CODE';
export const CODE_SENT = 'CODE_SENT';
export const VALIDATING_CODE = 'VALIDATING_CODE';
export const VALIDATED_CODE = 'VALIDATED_CODE';
export const GENERATING_NEW_PASSWORD = 'GENERATING_NEW_PASSWORD';
export const GENERATED_NEW_PASSWORD = 'GENERATED_NEW_PASSWORD';
export const SENDING_VERIFICATION_CODE_ERROR = 'SENDING_VERIFICATION_CODE_ERROR';
export const VALIDATING_ERROR = 'VALIDATING_ERROR';
export const GENERATING_NEW_PASSWORD_ERROR = 'GENERATING_NEW_PASSWORD_ERROR';

// Dashboard
export const FETCHING_DASHBOARD_OPEN_ORDERS = 'FETCHING_DASHBOARD_OPEN_ORDERS';
export const FETCHED_DASHBOARD_OPEN_ORDERS = 'FETCHED_DASHBOARD_OPEN_ORDERS';
export const FETCHING_DASHBOARD_OPEN_ORDERS_ERROR = 'FETCHING_DASHBOARD_OPEN_ORDERS_ERROR';

export const FETCHING_DASHBOARD_FAVORITE_VENDORS = 'FETCHING_DASHBOARD_FAVORITE_VENDORS';
export const FETCHED_DASHBOARD_FAVORITE_VENDORS = 'FETCHED_DASHBOARD_FAVORITE_VENDORS';
export const FETCHING_DASHBOARD_FAVORITE_VENDORS_ERROR = 'FETCHING_DASHBOARD_FAVORITE_VENDORS_ERROR';

export const FETCHING_DASHBOARD_SHIPPING_SOON = 'FETCHING_DASHBOARD_SHIPPING_SOON';
export const FETCHED_DASHBOARD_SHIPPING_SOON = 'FETCHED_DASHBOARD_SHIPPING_SOON';
export const FETCHING_DASHBOARD_SHIPPING_SOON_ERROR = 'FETCHING_DASHBOARD_SHIPPING_SOON_ERROR';

export const FETCHING_DASHBOARD_PAST_DUE_ORDERS = 'FETCHING_DASHBOARD_PAST_DUE_ORDERS';
export const FETCHED_DASHBOARD_PAST_DUE_ORDERS = 'FETCHED_DASHBOARD_PAST_DUE_ORDERS';
export const FETCHING_DASHBOARD_PAST_DUE_ORDERS_ERROR = 'FETCHING_DASHBOARD_PAST_DUE_ORDERS_ERROR';


// Open orders
export const FETCHING_OPEN_ORDERS = 'FETCHING_OPEN_ORDERS';
export const FETCHED_OPEN_ORDERS = 'FETCHED_OPEN_ORDERS'; 
export const FETCHING_OPEN_ORDERS_ERROR = 'FETCHING_OPEN_ORDERS_ERROR';
export const FETCHING_ANOTHER_OPEN_ORDERS_PAGE = 'FETCHING_ANOTHER_OPEN_ORDERS_PAGE';
export const FETCHING_OPEN_ORDERS_SLIDER_DATA = 'FETCHING_OPEN_ORDERS_SLIDER_DATA';
export const FETCHED_OPEN_ORDERS_SLIDER_DATA = 'FETCHED_OPEN_ORDERS_SLIDER_DATA';

// Favorite Vendors
export const FETCHING_FAVORITE_VENDORS = 'FETCHING_FAVORITE_VENDORS';
export const FETCHED_FAVORITE_VENDORS = 'FETCHED_FAVORITE_VENDORS';

// Shipping Soon
export const FETCHING_SHIPPING_SOON = 'FETCHING_SHIPPING_SOON';
export const FETCHED_SHIPPING_SOON = 'FETCHED_SHIPPING_SOON'; 
export const SHIPPING_SOON_ERROR = 'SHIPPING_SOON_ERROR';

// Past Due Orders
export const FETCHING_PAST_DUE_ORDERS = 'FETCHING_PAST_DUE_ORDERS';
export const FETCHED_PAST_DUE_ORDERS = 'FETCHED_PAST_DUE_ORDERS';
export const PAST_DUE_ORDER_ERROR = 'PAST_DUE_ORDER_ERROR';

// Budgeting
export const FETCHING_MONTHLY_BUDGETS = 'FETCHING_MONTHLY_BUDGETS';
export const FETCHED_MONTHLY_BUDGETS = 'FETCHED_MONTHLY_BUDGETS';
export const FETCHING_MONTHLY_BUDGETS_ERROR = 'FETCHING_MONTHLY_BUDGETS_ERROR';

export const FETCHING_CATEGORY_BUDGETS = 'FETCHING_CATEGORY_BUDGETS';
export const FETCHED_CATEGORY_BUDGETS = 'FETCHED_CATEGORY_BUDGETS';
export const FETCHING_CATEGORY_BUDGETS_ERROR = 'FETCHING_CATEGORY_BUDGETS_ERROR';

export const FETCHING_MARKET_BUDGETS = 'FETCHING_MARKET_BUDGETS';
export const FETCHED_MARKET_BUDGETS = 'FETCHED_MARKET_BUDGETS';
export const FETCHING_MARKET_BUDGETS_ERROR = 'FETCHING_MARKET_BUDGETS_ERROR';

// Support
export const FETCHING_VIDEOS = 'FETCHING_VIDEOS';
export const FETCHED_VIDEOS = 'FETCHED_VIDEOS';
export const FETCHING_VIDEOS_ERROR = 'FETCHING_VIDEOS_ERROR';
